linkerdNamespace: linkerd
createNamespaceMetadataJob: true
collector:
  enabled: true
  replicas: 1
  config:
    exporters:
      jaeger:
        endpoint: "jaeger-operator-jaeger-collector.addons.svc:14250"
        tls:
          insecure: true
jaeger:
  enabled: false