jaeger:
  create: true
  namespace: addons
  spec:
    strategy: production
    storage:
      type: elasticsearch
      options:
        es:
          server-urls: https://waniai-elasticsearch-es-http.addons.svc.cluster.local:9200
          username: elastic
          password: 0g0200T5OB7SeFwrw7vZX92t
          tls.enabled: true
          tls.skip-host-verify: true
          index-prefix: jaeger
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      hosts:
        - jaeger.monitor.wanaia.net
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
rbac:
  create: true
  clusterRole: true
