highAvailability: true
controlPlaneTracing: false
controlPlaneTracingNamespace: addons
enableEndpointSlices: true
controllerReplicas: 1
enablePodDisruptionBudget: true
identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIBjTCCATSgAwIBAgIRAKPhuuqOpOuPQYk14sHnr/owCgYIKoZIzj0EAwIwJTEj
  MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwNzE4MTg0
  MzA5WhcNMzUwNzE2MTg0MzA5WjAlMSMwIQYDVQQDExpyb290LmxpbmtlcmQuY2x1
  c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABAlKhsEvDu+ZA9eJ
  s13XK5gtzo53vASJSb5jDKNoz4GwEry90KGZbhanqtiN8A2PF7ktBMYj8pcGAJsf
  shDGz5ujRTBDMA4GA1UdDwEB/wQEAwIBBjASBgNVHRMBAf8ECDAGAQH/AgEBMB0G
  A1UdDgQWBBSN/vKsobnQGaFrvLvkJq9rrePDmDAKBggqhkjOPQQDAgNHADBEAiBS
  C9OeoXJ7NXZSEncRVBIaph48ZcOrTF7BkO5v1jg83wIga1bx5ZsFBHDFamnJYlu3
  WNZvpqWNhUt196aFnJQ2hL4=
  -----END CERTIFICATE-----
identityTrustDomain: ""
proxy:
  resources:
    cpu:
      request: 100m
    memory:
      limit: 250Mi
      request: 20Mi
  control:
    streams:
      initialTimeout: "3s"
      idleTimeout: "5m"
      lifetime: "1h"
  metrics:
    hostnameLabels: false
  tracing:
    enable: false
    traceServiceName: linkerd-proxy
    collector:
      endpoint: ""
      meshIdentity:
        serviceAccountName: ""
proxyInit:
  runAsRoot: false
  closeWaitTimeoutSecs: 0
identity:
  externalCA: false
  serviceAccountTokenProjection: true
  issuer:
    clockSkewAllowance: 20s
    issuanceLifetime: 24h0m0s
    tls:
      crtPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBszCCAVmgAwIBAgIRANshb061otIG6mFvfZxfdhwwCgYIKoZIzj0EAwIwJTEj
        MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwNzE4MTg0
        MzE3WhcNMjYwNzE4MTg0MzE3WjApMScwJQYDVQQDEx5pZGVudGl0eS5saW5rZXJk
        LmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQvM0vosNuW
        7Ff5jaSTrVheylBw+ooNLNZ4VmkvYzfxJJgCOyjMDL/nIhRfDmITRFIsRFAOILJb
        ogbLB1P3dYYro2YwZDAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIB
        ADAdBgNVHQ4EFgQUdJG08rPUNsxYO45J5K7/Qk9XcYQwHwYDVR0jBBgwFoAUjf7y
        rKG50Bmha7y75Cava63jw5gwCgYIKoZIzj0EAwIDSAAwRQIhALF7ba4yHkUvMk3j
        bwewp7IJdSsg26e/9ArjAaTGVJhAAiATbvG4oSUJXALWS8v9WoymPR0GmkvYswu9
        zCFjUS0qEw==
        -----END CERTIFICATE-----
      keyPEM: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIL64pfjRsztMDgwnmJPxckJotrRlpZuTvdQP4lf9S2XdoAoGCCqGSM49
        AwEHoUQDQgAELzNL6LDbluxX+Y2kk61YXspQcPqKDSzWeFZpL2M38SSYAjsozAy/
        5yIUXw5iE0RSLERQDiCyW6IGywdT93WGKw==
        -----END EC PRIVATE KEY-----
prometheusUrl: ""
podMonitor:
  enabled: false
  scrapeInterval: 10s
  scrapeTimeout: 10s
  labels: {}
  controller:
    enabled: true
    namespaceSelector: |
      matchNames:
        - {{ .Release.Namespace }}
        - linkerd-viz
        - linkerd-jaeger
egress:
  globalEgressNetworkNamespace: linkerd-egress