highAvailability: true
controlPlaneTracing: false
controlPlaneTracingNamespace: linkerd-jaeger
enableEndpointSlices: true
controllerReplicas: 3
enablePodDisruptionBudget: true
identityTrustAnchorsPEM: |
  -----BEGIN CERTIFICATE-----
  MIIBoDCCAUWgAwIBAgIUVH82T+hFIboMoBUKntRm4aE+304wCgYIKoZIzj0EAwIw
  JTEjMCEGA1UEAwwacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwNzE4
  MTYxNjIzWhcNMzUwNzE2MTYxNjIzWjAlMSMwIQYDVQQDDBpyb290LmxpbmtlcmQu
  Y2x1c3Rlci5sb2NhbDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABI3mEHU6aqSD
  z32+PDsj0sKLriiB6tnMRT1V6SMTTDfr5IoQKDgTB1z0m/Uk1yh3rQOFolyEvJKj
  p6M/h77KlLujUzBRMB0GA1UdDgQWBBTOUWI9g9o4ZbllGfwqIuY3yq26kzAfBgNV
  HSMEGDAWgBTOUWI9g9o4ZbllGfwqIuY3yq26kzAPBgNVHRMBAf8EBTADAQH/MAoG
  CCqGSM49BAMCA0kAMEYCIQC03F3eOo5l4VsrVPHQshoBjXZWsWHP78eRh7AzEM+n
  xwIhAPGvTAFp5NY1HdHyWuC296lwAnoX60YRL7GvxUJb0d+B
  -----END CERTIFICATE-----
identityTrustDomain: ""
proxy:
  outboundConnectTimeout: 1000ms
  inboundConnectTimeout: 100ms
  outboundDiscoveryCacheUnusedTimeout: "5s"
  inboundDiscoveryCacheUnusedTimeout: "90s"
  resources:
    cpu:
      request: 100m
    memory:
      limit: 250Mi
      request: 20Mi
  control:
    streams:
      initialTimeout: "3s"
      idleTimeout: "5m"
      lifetime: "1h"
  metrics:
    hostnameLabels: false
  tracing:
    enable: false
    traceServiceName: linkerd-proxy
    collector:
      endpoint: ""
      meshIdentity:
        serviceAccountName: ""
identity:
  externalCA: false
  serviceAccountTokenProjection: true
  issuer:
    clockSkewAllowance: 20s
    issuanceLifetime: 24h0m0s
    tls:
      crtPEM: |
        -----BEGIN CERTIFICATE-----
        MIIBkzCCATigAwIBAgIUFDKajca2G3y7HGi/f660wt6G2t8wCgYIKoZIzj0EAwIw
        JTEjMCEGA1UEAwwacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwHhcNMjUwNzE4
        MTYxNjM2WhcNMjYwNzE4MTYxNjM2WjApMScwJQYDVQQDDB5pZGVudGl0eS5saW5r
        ZXJkLmNsdXN0ZXIubG9jYWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQJjF3g
        hD2wESbOHL27V+zANLGY5nKdzL0NJZADbDrdmO3HUMuQfWzaDOp3aRtA/HwaMfcf
        RyQcxiMLFGlBCwzpo0IwQDAdBgNVHQ4EFgQUSvk91V4oHElS4g5yXCEz/fCFwVAw
        HwYDVR0jBBgwFoAUzlFiPYPaOGW5ZRn8KiLmN8qtupMwCgYIKoZIzj0EAwIDSQAw
        RgIhAMDVuR9UQgtwEO4QtR67GdZgFZtFKCDYwmxwmHAJ86fMAiEAtRnutrb2ywCf
        Yl/P3cXjkx3Etj0wxGQQ6bYue/WTPm8=
        -----END CERTIFICATE-----
      keyPEM: |
        -----BEGIN EC PRIVATE KEY-----
        MHcCAQEEIFMEP/8sJSYvMDX0lv06prJG6UuhfCHx9R84N4WUhyv/oAoGCCqGSM49
        AwEHoUQDQgAECYxd4IQ9sBEmzhy9u1fswDSxmOZyncy9DSWQA2w63Zjtx1DLkH1s
        2gzqd2kbQPx8GjH3H0ckHMYjCxRpQQsM6Q==
        -----END EC PRIVATE KEY-----
prometheusUrl: ""
podMonitor:
  enabled: false
  scrapeInterval: 10s
  scrapeTimeout: 10s
  labels: {}
  controller:
    enabled: true
    namespaceSelector: |
      matchNames:
        - {{ .Release.Namespace }}
        - linkerd-viz
        - linkerd-jaeger
  serviceMirror:
    enabled: true
  proxy:
    enabled: true
egress:
  globalEgressNetworkNamespace: linkerd-egress