releases:
  - name: rook-ceph
    namespace: rook-ceph
    createNamespace: true
    chart: wanaia/rook-ceph
    version: v1.17.2
    labels:
      component: rook-ceph
    values:
      - ../../rook-ceph/v1.17.2/examples/values.{{ requiredEnv "COMPONENT_ENV" }}.yaml
  - name: rook-ceph-cluster
    namespace: rook-ceph
    createNamespace: true
    chart: wanaia/rook-ceph-cluster
    version: v1.17.2
    labels:
      component: rook-ceph-cluster
    values:
      - ../../rook-ceph-cluster/v1.17.2/examples/values.{{ requiredEnv "COMPONENT_ENV" }}.yaml
