# secret with the toolserver credentials
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kagent.fullname" . }}-toolserver-secret
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" . | nindent 4 }}
type: Opaque
data:
  grafana: {{ .Values.tools.grafana.apiKey | b64enc | quote }}
  prometheus: {{ .Values.tools.prometheus.password | b64enc | quote }}