apiService:
  create: true
  annotations: {}
  insecureSkipTLSVerify: true
  caBundle: ""
priorityClassName: system-cluster-critical
containerPort: 10250
hostNetwork:
  enabled: false
replicas: 1
revisionHistoryLimit:
updateStrategy: {}
defaultArgs:
  - --cert-dir=/tmp
  - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
  - --kubelet-use-node-status-port
  - --metric-resolution=15s
metrics:
  enabled: false
serviceMonitor:
  enabled: false
  additionalLabels: {}
  interval: 1m
  scrapeTimeout: 10s
  metricRelabelings: []
  relabelings: []
resources:
  requests:
    cpu: 100m
    memory: 200Mi