apiVersion: v2
dependencies:
- condition: k8s-agent.enabled
  name: k8s-agent
  repository: file://../agents/k8s
  version: 0.4.2
- condition: kgateway-agent.enabled
  name: kgateway-agent
  repository: file://../agents/kgateway
  version: 0.4.2
- condition: istio-agent.enabled
  name: istio-agent
  repository: file://../agents/istio
  version: 0.4.2
- condition: promql-agent.enabled
  name: promql-agent
  repository: file://../agents/promql
  version: 0.4.2
- condition: observability-agent.enabled
  name: observability-agent
  repository: file://../agents/observability
  version: 0.4.2
- condition: argo-rollouts-agent.enabled
  name: argo-rollouts-agent
  repository: file://../agents/argo-rollouts
  version: 0.4.2
- condition: helm-agent.enabled
  name: helm-agent
  repository: file://../agents/helm
  version: 0.4.2
- condition: cilium-policy-agent.enabled
  name: cilium-policy-agent
  repository: file://../agents/cilium-policy
  version: 0.4.2
- condition: cilium-manager-agent.enabled
  name: cilium-manager-agent
  repository: file://../agents/cilium-manager
  version: 0.4.2
- condition: cilium-debug-agent.enabled
  name: cilium-debug-agent
  repository: file://../agents/cilium-debug
  version: 0.4.2
description: A Helm chart for kagent, built with Autogen
name: kagent
type: application
version: 0.4.2
