# kubectl create secret generic kagent-openai -n kagent --from-literal=OPENAI_API_KEY=your_openai_api_key_here
replicaCount: 1
providers:
  default: openAI
  openAI:
    provider: OpenAI
    model: "gpt-4.1-mini"
    apiKeySecretRef: kagent-openai
    apiKeySecretKey: OPENAI_API_KEY
controller:
  loglevel: "info"
  watchNamespaces: []
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
tools:
  loglevel: "debug"
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  prometheus:
    url: "prometheus.kagent.svc.cluster.local:9090"
    username: ""
    password: ""
  grafana:
    url: "http://grafana.kagent.svc.cluster.local:3000"
    apiKey: ""
ui:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  env: []
service:
  type: ClusterIP
  ports:
    ui:
      port: 80
      targetPort: 8080
    app:
      port: 8081
      targetPort: 8081
    controller:
      port: 8083
      targetPort: 8083
    tools:
      port: 8084
      targetPort: 8084
    querydoc:
      port: 8085
      targetPort: 8085

otel:
  tracing:
    enabled: false
    exporter:
      otlp:
        endpoint: http://host.docker.internal:4317
        timeout: 15
        insecure: true
k8s-agent:
  enabled: true
kgateway-agent:
  enabled: true
istio-agent:
  enabled: false
promql-agent:
  enabled: true
observability-agent:
  enabled: true
argo-rollouts-agent:
  enabled: false
helm-agent:
  enabled: false
cilium-policy-agent:
  enabled: false
cilium-manager-agent:
  enabled: false
cilium-debug-agent:
  enabled: false
