replicas: 1
createConfigmap: true
podPortName: grafana
gossipPortName: gossip
serviceMonitor:
  enabled: false
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  path: /
  pathType: Prefix
  hosts:
    - grafana.wanaia.local
adminUser: admin
admin:
  existingSecret: ""
  userKey: admin-user
  passwordKey: admin-password
