prometheusUrl: "http://vmselect-victoria-metrics-k8s-stack.addons.svc:8481/select/0/prometheus"
jaegerUrl: "http://jaeger.sm.wanaia.net:30080"
prometheus:
  enabled: false
dashboard:
  enforcedHostRegexp: "^(localhost|127\\.0\\.0\\.1|web\\.linkerd\\.svc\\.cluster\\.local|web\\.linkerd\\.svc|\\[::1\\]|linkerd\\.sm\\.wanaia\\.net)(:\\d+)?$"
