apiVersion: operator.victoriametrics.com/v1beta1
kind: VMCluster
metadata:
  name: vmcluster
  namespace: addons
spec:
  retentionPeriod: "1w" # 保留1周数据
  vmstorage:
    replicaCount: 1
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi
    storage:
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
          accessModes: ["ReadWriteOnce"]
          storageClassName: local-path
          resources:
            requests:
              storage: 20Gi
  vmselect:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
  vminsert:
    replicaCount: 1
    resources:
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: vmalertmanager
  namespace: addons
spec:
  replicaCount: 1
  selectAllByDefault: true
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: vmalert
  namespace: addons
spec:
  replicaCount: 1
  selectAllByDefault: true
  notifier:
    url: http://vmalertmanager-vmalertmanager.addons.svc.cluster.local:9093
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi
  remoteWrite:
    url: http://vminsert-vmcluster.addons.svc.cluster.local:8480/insert/0/prometheus/
  remoteRead:
    url: http://vmselect-vmcluster.addons.svc.cluster.local:8481/select/0/prometheus/
  datasource:
    url: http://vmselect-vmcluster.addons.svc.cluster.local:8481/select/0/prometheus/
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: vmagent
  namespace: addons
spec:
  selectAllByDefault: true
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  replicaCount: 1
  remoteWrite:
    - url: "http://vminsert-vmcluster.addons.svc.cluster.local:8480/insert/0/prometheus/api/v1/write"
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMNodeScrape
metadata:
  name: node-exporter
spec:
  path: /metrics
  port: "9100"
  scrape_interval: 15s
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: victoria-metrics-ingress
  namespace: addons
spec:
  ingressClassName: nginx
  rules:
    - host: vmselect-vmcluster.wanaia.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmselect-vmcluster
                port:
                  number: 8481
    - host: vminsert-vmcluster.wanaia.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vminsert-vmcluster
                port:
                  number: 8480
    - host: vmagent.wanaia.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vmagent-vmagent
                port:
                  number: 8429
