repositories:
  - name: wanaia
    url: https://wanaia.github.io/helm-charts/

helmfiles:
  # - path: storage/helmfile.yaml
  #   selectors:
  #     - component=rook-ceph
  #     - component=rook-ceph-cluster
  - path: ingress-nginx/helmfile.yaml
    selectors:
      - component=ingress-nginx
  - path: kagent/helmfile.yaml
    selectors:
      - component=kagent-crds
      - component=kagent
      - component=jaeger-operator
# export COMPONENT_ENV=local
# helmfile apply -f wanaia-helmfile/helmfile.yaml
