apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: waniai-elasticsearch
  namespace: addons
spec:
  version: 8.8.0
  nodeSets:
    - name: master
      count: 1
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: waniai-kibana
  namespace: addons
spec:
  version: 8.8.0
  count: 1
  elasticsearchRef:
    name: waniai-elasticsearch
  config:
    server.publicBaseUrl: "https://kibana.log.wanaia.net:30443"
    xpack.security.secureCookies: true
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kibana
  namespace: addons
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/proxy-ssl-verify: "false"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - kibana.log.wanaia.net
      secretName: kibana-tls
  rules:
    - host: kibana.log.wanaia.net
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: waniai-kibana-kb-http
                port:
                  number: 5601
