apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: waniai-elasticsearch
  namespace: addons
spec:
  version: 8.8.0
  nodeSets:
    - name: master
      count: 1
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            storageClassName: local-path
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 20Gi
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: waniai-kibana
  namespace: addons
spec:
  version: 8.8.0
  count: 1
  elasticsearchRef:
    name: waniai-elasticsearch
