{{- if eq .Values.providers.default "openAI" }}
apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: {{ include "kagent.fullname" . }}-querydoc
  namespace: {{ include "kagent.namespace" . }}
spec:
  config:
    streamableHttp:
      sseReadTimeout: 5m0s
      timeout: 30s
      url: {{ printf "http://localhost:%v/mcp" .Values.service.ports.querydoc.targetPort }}
  description: "Documentation Query Tool Server"
{{- end }}