apiVersion: kagent.dev/v1alpha1
kind: ToolServer
metadata:
  name: {{ include "kagent.fullname" . }}-tool-server
  namespace: {{ include "kagent.namespace" . }}
spec:
  config:
    streamableHttp:
      sseReadTimeout: 5m0s
      timeout: 30s
      url: {{ printf "http://localhost:%v/mcp" .Values.service.ports.tools.targetPort }}
  description: "KAgent Tool Server"
