{{- $dot := . }}
{{- $model := index $dot.Values.providers $dot.Values.providers.default  }}
---
apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: {{ include "kagent.defaultModelConfigName" $dot | quote }}
  namespace: {{ include "kagent.namespace" . }}
  labels:
    {{- include "kagent.labels" $dot | nindent 4 }}
spec:
  {{- with $model }}
  provider: {{ .provider | quote }}
  model: {{ .model | quote }}
  {{- if $model.apiKeySecretRef }}
  apiKeySecretRef: {{.apiKeySecretRef}}
  {{- end }}
  {{- if $model.apiKeySecretKey }}
  apiKeySecretKey: {{.apiKeySecretKey}}
  {{- end }}
  {{ $dot.Values.providers.default }}:
  {{- toYaml $model.config | nindent 4 }}
  {{- end}}