controller:
  name: controller
  enableAnnotationValidations: true
  containerName: controller
  containerPort:
    http: 80
    https: 443
  dnsPolicy: ClusterFirst
  networkPolicy:
    enabled: false
  electionID: ""
  ingressClassResource:
    name: nginx
    enabled: true
  ingressClass: nginx
  kind: Deployment
  progressDeadlineSeconds: 0
  minReadySeconds: 0
  tolerations: []
  affinity: {}
  nodeSelector:
    kubernetes.io/os: linux
  replicaCount: 1
  minAvailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
  service:
    enabled: true
    type: NodePort
    nodePorts:
      http: "30080"
      https: "30043"
  admissionWebhooks:
    name: admission
    annotations: {}
    enabled: true
    extraEnvs: []
    failurePolicy: Fail
    port: 8443
    certificate: "/usr/local/certificates/cert"
    key: "/usr/local/certificates/key"
    namespaceSelector: {}
    objectSelector: {}
    labels: {}
    service:
      annotations: {}
      externalIPs: []
      loadBalancerSourceRanges: []
      servicePort: 443
      type: ClusterIP
    createSecretJob:
      name: create
      activeDeadlineSeconds: 0
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      resources: {}
    patchWebhookJob:
      name: patch
      activeDeadlineSeconds: 0
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        allowPrivilegeEscalation: false
        seccompProfile:
          type: RuntimeDefault
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      resources: {}
    certManager:
      enabled: false
      rootCert:
        duration: ""
        revisionHistoryLimit: 0
      admissionCert:
        duration: ""
        revisionHistoryLimit: 0
  metrics:
    port: 10254
    portName: metrics
    enabled: false
    service:
      enabled: true
      annotations: {}
      labels: {}

      externalIPs: []
      loadBalancerSourceRanges: []
      servicePort: 10254
      type: ClusterIP
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      annotations: {}
      namespace: ""
      namespaceSelector: {}
      scrapeInterval: 30s
      targetLabels: []
      relabelings: []
      metricRelabelings: []
      labelLimit: 0
      labelNameLengthLimit: 0
      labelValueLengthLimit: 0
      sampleLimit: 0
      targetLimit: 0
    prometheusRule:
      enabled: false
      additionalLabels: {}
      annotations: {}
      rules: []
  lifecycle:
    preStop:
      exec:
        command:
          - /wait-shutdown
  priorityClassName: ""
revisionHistoryLimit: 10
