controller:
  name: controller
  enableAnnotationValidations: true
  containerName: controller
  containerPort:
    http: 80
    https: 443
  dnsPolicy: ClusterFirst
  networkPolicy:
    enabled: false
  electionID: ""
  ingressClassResource:
    name: nginx
    enabled: true
  ingressClass: nginx
  kind: Deployment
  progressDeadlineSeconds: 0
  minReadySeconds: 0
  tolerations: []
  affinity: {}
  nodeSelector:
    kubernetes.io/os: linux
  replicaCount: 1
  minAvailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 90Mi
  service:
    enabled: true
    type: NodePort
    nodePorts:
      http: "30080"
      https: "30043"
  metrics:
    port: 10254
    portName: metrics
    enabled: false
    service:
      enabled: true
      annotations: {}
      labels: {}

      externalIPs: []
      loadBalancerSourceRanges: []
      servicePort: 10254
      type: ClusterIP
    serviceMonitor:
      enabled: false
      additionalLabels: {}
      annotations: {}
      namespace: ""
      namespaceSelector: {}
      scrapeInterval: 30s
      targetLabels: []
      relabelings: []
      metricRelabelings: []
      labelLimit: 0
      labelNameLengthLimit: 0
      labelValueLengthLimit: 0
      sampleLimit: 0
      targetLimit: 0
    prometheusRule:
      enabled: false
      additionalLabels: {}
      annotations: {}
      rules: []
  lifecycle:
    preStop:
      exec:
        command:
          - /wait-shutdown
  priorityClassName: ""
revisionHistoryLimit: 10
