name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: install helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: v3.8.1

      - name: package charts
        run: |
          mkdir -p packaged-charts
          find . -name Chart.yaml ! -path "*/charts/*" | while read chart; do
            chartDir=$(dirname "$chart")
            helm package "$chartDir" -d packaged-charts
          done

      - name: generate index.yaml
        run: |
          cd packaged-charts
          helm repo index . --url https://wanaia.github.io/helm-charts
          cd ..

      - name: deploy gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.RUNNER_GITHUB_TOKEN }}
          publish_dir: ./packaged-charts